### ISSUE TITLE
Consumables: Both Strategic Strike types should share the same activation key

### ISSUE THREAD

**Issue by TheFifthHorseman** [MechWarriorOnline/issue-tracker#117]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
Functionally, both of those are the same category ("Strategic Strike" as named in the Skill Tree UI) and share a cap.
Currently, the keybinds to activate consumables by type are separate for Air Strike and Artillery Strike.

Proposal: Change the control configuration so that activation of Strategic Strike consumables by type is a single keybind shared by both types.

**Comment by Tarogato-MWO** [comment]
Downvoted, as I prefer my two different strike types on two different keys, it subconsciously reminds me how to line up and use my strike. 

BUT. It would be nice to have an ADDITIONAL keybind option that applies to BOTH strike types.

**Comment by rwil02** [comment]
@Tarogato-MWO Correspondingly.
I have 2 UAVs.  Slot 1 set to "Insert", Slot 2 set to "Home", I ALSO have "UAV" bound to a 3rd key I never use.
So why does hitting "Home" twice end up launching both my UAVs?

**Comment by DruTheBlue** [comment]
So in the game settings there are both key binding options for the specific slot that the consumable is in and there are also key bindings that activate the designated type of consumable regardless of what slot it is in. So if you have a UAV in Consumable Slot 1 and an Air Strike in Slot 2 you would be able to set both  activate Consumable Slot 1 and activate Air Strike to the same key. When you are pressing "home" twice it is because the binding you are using is just set up to call a uav without checking for what slot its in. Deactivate those bindings and set up the slot specific ones.

**Comment by rwil02** [comment]
![mwo 07 10 2017-18 54 46](https://user-images.githubusercontent.com/6047913/28006020-8ef2cf14-65a1-11e7-8a02-d30de2d13c05.jpg)
I'd agree, except that I do NOT have hot keys defined for the consumables themselves, just the slots.

**Comment by tauSentry** [comment]
Administrivia...  

Doing a little cleanup in the Issue Tracker.  
Since this issue (in it's current form) seems to be fairly controversial, I propose the following:  
1. I will go ahead and close this issue.
2. Open a new issue with an adjusted proposal to address the objections to this one. Perhaps something along the lines of [Tarogato's suggestion](https://github.com/MechWarriorOnline/issue-tracker/issues/117#issuecomment-311058379). For example:  
`Proposal: Add a New key-bind option which activates the first unused Strategic Strike consumable (any type) from a Mech's consumable slots, i.e. each successive press activates the next unused Strike of any type in the list of equipped consumables.`

UPDATE:  
I went ahead and created Issue #211.

Will close this issue.

**Comment by tauSentry** [comment]
Refer to Issue #211.
