### ISSUE TITLE
Autorun stops while typing, but only intermittently 

### ISSUE THREAD

**Issue by coreyfro** [MechWarriorOnline/issue-tracker#124]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---

Sometimes autorun works while typing...sometimes it doesn't.  When it does, it does for the whole match.  When it doesn't, it doesn't for the whole match.

*Additional information provided by @RX78NT1*  
> My setup is that I have throttle decay on and 'set throttle to 100%' bound to E. Sometimes during a match bringing up the scoreboard (or the map) when I've used 100% throttle will stop me dead in my tracks, sometimes it won't. It will then be consistent that way for the whole match as the OP said, but the next match I join there's a 50/50 chance opening the scoreboard or battlegrid will cause me to stop.  I have no clue what causes it but it's infuriating due to being inconsistent.

**Comment by tauSentry** [comment]
Administrivia...
Can you provide a little more context for anyone who isn't immediately familiar with the problem.  
For example, by *autorun* I assume you mean setting a constant speed with the numpad, and when you mention "sometimes it doesn't" can you describe the behavior.

**Comment by RX78NT1** [comment]
This happens to me as well. I can provide a little more information.

My setup is that I have throttle decay on and 'set throttle to 100%' bound to E. Sometimes during a match bringing up the scoreboard (or the map) when I've used 100% throttle will stop me dead in my tracks, sometimes it won't. It will then be consistent that way for the whole match as the OP said, but the next match I join there's a 50/50 chance opening the scoreboard or battlegrid will cause me to stop.  I have no clue what causes it but it's infuriating due to being inconsistent.

**Comment by Tarogato-MWO** [comment]
Interesting. I think I used to experience this issue, but I haven't had it happen to me in many months. I also use "Set Throttle To 100%"

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Patch 1.4.131 (19-Sep-2017)](https://mwomercs.com/news/2017/09/1891-patch-notes-14131-19sep2017), this bug is supposedly fixed.

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Hotfix (21-Sep-2017)](https://mwomercs.com/news/2017/09/1896-hotfix-scheduled-for-21sep2017), the fix for this bug is being __*reverted*__ because it caused new problems related to Mech inputs.

No date has been specified yet for when this issue will be reevaluated.

Reopening issue :(

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Patch 1.4.132 (17-Oct-2017)](https://mwomercs.com/news/2017/10/1910-patch-notes-14132-17oct2017), this fix for this bug has been re-added.
