### ISSUE TITLE
Heat Containment nodes only affect base heat, not heat sinks.

### ISSUE THREAD

**Issue by dtandersen** [MechWarriorOnline/issue-tracker#161]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
[Dev reported](https://mwomercs.com/forums/topic/251016-heat-generation-or-cool-run-whats-better/page__view__findpost__p__5745303):

>Heat Containment factors in the total heat threshold of the 'Mech (Base + Value gained through your heatsinks,

but [heat sinks aren't actually taken into consideration](https://mwomercs.com/forums/topic/251276-heat-containment-testing/page__view__findpost__p__5755281).

Current formula appears to be  
`30 * (1 + heatContainment) + 2 * engine HS + 1.5 * external HS`  
instead of  
`(30 + 2 * engine HS + 1.5 * external HS) * (1 + heatContainment)`

**Comment by tauSentry** [comment]
Administrivia...  
There was also a thread on [/r/OutreachHPG](https://www.reddit.com/r/OutreachHPG/) or [/r/mwo](https://www.reddit.com/r/mwo/) that touched on this issue too. Can you find that link and add it in.

**Comment by Tyler799** [comment]
Important question: Was the testing done in a private match, or testing grounds? If testing grounds, it's pretty irrelevant. 

For sake of readability, could you put the two formulas on seperate lines instead having the first one be offset? IE:

[30 * (1 + heatContainment)] + (2 * engine HS) + (1.5 * external HS)
[30 + (2 * engine HS) + (1.5 * external HS)] * (1 + heatContainment)

(Note: The 2x engine and 1.5 * external only applies assuming DHS, which is a fairly good assumption)

Though seeing it now like that, I get what you're saying. The heat containment is being applied before the heatsink values are added, instead of after.

For sake of speediness, I think I'll toss an e-mail to MWO support on the issue. 

In an example, let's try the absolute worst-case scenario. This Black Knight with DHS and 19 total heatsinks: http://mwo.smurfy-net.de/mechlab#i=323&l=4841abad699c652d446262953e39ba32bc86288b

current formula:

[30 * (1 + .15)] + (2 * 10) + (1.5 * 9) = 68 max heat

one it should be:

[30 + (2 * 10) + (1.5 * 9)] * (1 + 0.15) = 73 max heat

That's not a huge difference, even in a worst-case scenario, but it's still frustrating. It's the value of a light PPC's heat!

**Comment by Tarogato-MWO** [comment]
I can confirm/corroborate this issue, I have independently tested it in game against my own theoretical calculations.

**Comment by Talisman11** [comment]
Is there a chance that this affets Cool Run nodes as well? As in, the increased dissipation only (incorrectly) applies to base dissipation without consideration for external HS dissipation?

**Comment by TheFifthHorseman** [comment]
I've seen some claims that Cool Run works only affects external heat sinks.

**Comment by Rydiak** [comment]
Tarogato also did extensive testing with Cool Run, and it works perfectly fine with both engine heatsinks and external heatsinks.  Only Heat Containment has no affect on heatsinks whatsoever.

**Comment by tauSentry** [comment]
Update:  
PGI Developer Chris Lowrey [posted an announcement](https://mwomercs.com/forums/topic/256505-a-note-on-heat-containment) that this issue has been confirmed and will be fixed in the September patch :)

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Patch 1.4.131 (19-Sep-2017)](https://mwomercs.com/news/2017/09/1891-patch-notes-14131-19sep2017), this bug is supposedly fixed.

**Comment by tauSentry** [comment]
@Tarogato-MWO  
Can you confirm that this is now fixed?
